### ISSUE TITLE
Support mmc.getTaggedImage

### ISSUE THREAD

**Issue by oeway** [micro-manager/pymmcore#17] opened 2020-09-05 00:09 UTC
The java interface has the `getTaggedImage` function, perhaps would be good to also make it available in the Python binding?

**Comment by marktsuchida** [comment] 2020-09-10 16:59
@oeway This is a good point. The problem is that `TaggedImage` is a Java type, and one that we would like to phase out in the long term due to multiple issues (it exposes public data fields (bad in Java unlike in Python), and uses an antiquated version of `JSONObject` as part of its API).

(Also, much of the logic for putting together a `TaggedImage` is in `MMCoreJ.i`, rather than the common MMCore code.)

It would be nice to have something similar in Python, though. If adding such a thing, it would be good to learn also from a few more design mistakes that `TaggedImage` made: it puts metadata from different sources into a single bag, and string-concatenates device and property names with `"-"`, so that unambiguous parsing is not possible.

**Comment by tlambert03** [comment] 2023-08-17 15:40
fwiw, this was added to pymmcore-plus in https://github.com/pymmcore-plus/pymmcore-plus/pull/246

**Comment by tlambert03** [comment] 2024-09-27 13:22
safe to close this issue as not planned @marktsuchida ?

**Comment by marktsuchida** [comment] 2024-10-02 22:07
Yes, the recommendation should be to use pymmcore-plus. There may be further improvements in MMCore and its API (rather than pymmcore, probably) to reduce overhead or more accurately define timing/concurrency, but that's a whole nother topic.

**Closed by marktsuchida** 2024-10-02 22:07 UTC
